version: '3.8'

networks:
  marketflow-net:
    driver: bridge

services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092" # internal
      - "9094:9094" # external
    environment:
      KAFKA_CLUSTER_ID: "MarketFlowCluster0"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_CLEANUP_POLICY: delete
    volumes:
      - ./data/kafka:/tmp/kraft-combined-logs
    networks:
      - marketflow-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_NAME: "MarketFlowCluster0"
    depends_on:
      - kafka
    networks:
      - marketflow-net

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=hdfs-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./data/hdfs/namenode:/hadoop/dfs/name
    networks:
      - marketflow-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    ports:
      - "50075:50075"
      - "50010:50010"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./data/hdfs/datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - marketflow-net

  spark-master:
    build: ./spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"   # Spark Master port
      - "8090:8090"
    command: >
      bash -c "/opt/spark/sbin/start-master.sh &&
               tail -f /opt/spark/logs/spark--org.apache.spark.deploy.master*.out"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8090
      - SPARK_LOG_DIR=/opt/spark/logs
    volumes:
      - ./spark-jobs:/opt/spark-jobs
      - ./data/spark/logs:/opt/spark/logs
    networks:
      - marketflow-net

  spark-worker-1:
    image: apache/spark:3.5.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8091:8091"
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
               tail -f /opt/spark/logs/spark--org.apache.spark.deploy.worker*.out"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_WEBUI_PORT=8091
      - SPARK_LOG_DIR=/opt/spark/logs
    volumes:
      - ./data/spark/:/opt/spark-data
      - ./data/spark/logs:/opt/spark/logs
    networks:
      - marketflow-net

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MarketFlowCluster
      - CASSANDRA_SEEDS=cassandra
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    volumes:
      - ./data/cassandra:/var/lib/cassandra
      - ./schema.cql:/schema.cql
    networks:
      - marketflow-net
